#General
work dir: mongolian_samples
slimfile: OoA3pop.slim
pop: p2
sample sizes: [5, 2, 1, 3, 3, 3, 1, 3, 4, 3, 3, 3, 4, 3, 4, 3, 3, 4, 8, 5]
years sampled: [5550, 5175, 3050, 2825, 2525, 1775, 1425, 1375, 1325, 1250, 1150, 1125, 1025, 950, 900, 800, 500, 325, 300, 175]
ploidy: 2

#Simulation
reps: 2500
selection gen: 200 # Gens before first sampling
selection coeff bounds: [0.005, 0.5]
mut rate: 1.29e-8
slim path: /proj/dschridelab/lswhiteh/timesweeper/src/SLiM/build/slim
gen time: 25

#TS
input vcf: /pine/scr/l/s/lswhiteh/timesweeper-experiments/empirical_model/vcfs/test_merged.vcf
afs model path: /pine/scr/l/s/lswhiteh/timesweeper-experiments/empirical_model/mongolian_samples/trained_models/mongolian_samples_TimeSweeper_afs
hfs model path: /pine/scr/l/s/lswhiteh/timesweeper-experiments/empirical_model/mongolian_samples/trained_models/mongolian_samples_TimeSweeper_hfs
