#General
work dir: /pine/scr/l/s/lswhiteh/timesweeper-experiments/empirical_model/OoA_samples_constant_sampling_uni_selcoeff
slimfile: /pine/scr/l/s/lswhiteh/timesweeper-experiments/empirical_model/OoA3pop.slim
pop: p2
sample sizes: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
years sampled: [4750, 4500, 4250, 4000, 3750, 3500, 3250, 3000, 2750, 2500, 2250, 2000, 1750, 1500, 1250, 1000, 750, 500, 250, 0]
ploidy: 2

#Simulation
reps: 2500
selection gen: 50 # Gens before first sampling
selection coeff bounds: [0.0, 0.05]
mut rate: 1.29e-8
slim path: slim
gen time: 25
