#General
work dir: sample_size_10_benchmark
slimfile: ../../slimfiles/onePop-selectiveSweep-vcf.slim

sample sizes: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
ploidy: 2
gens sampled: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190]

#Simulation
reps: 100
slim path: slim
